"""HTTP routers."""

from app.routers import (
    activities,
    agents,
    assignment_rules,
    attribution,
    auth,
    calls,
    companies,
    contacts,
    deals,
    drafts,
    forecasts,
    health,
    inbox,
    leads,
    messages,
    msa,
    netsuite,
    payments,
    pipeline_stages,
    reports,
    sequences,
    sms,
    tracking,
    workflows,
    workspaces,
)
from app.routers.webhooks import posthog as webhooks_posthog
from app.routers.webhooks import resend as webhooks_resend
from app.routers.webhooks import stripe as webhooks_stripe
from app.routers.webhooks import twilio as webhooks_twilio

__all__ = [
    "activities",
    "agents",
    "assignment_rules",
    "attribution",
    "auth",
    "calls",
    "companies",
    "contacts",
    "deals",
    "drafts",
    "forecasts",
    "health",
    "inbox",
    "leads",
    "messages",
    "msa",
    "netsuite",
    "payments",
    "pipeline_stages",
    "reports",
    "sequences",
    "sms",
    "tracking",
    "webhooks_posthog",
    "webhooks_resend",
    "webhooks_stripe",
    "webhooks_twilio",
    "workflows",
    "workspaces",
]
