"""AiDraft model — AI-generated content awaiting human review."""

import enum
from datetime import datetime
from uuid import UUID

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base
from app.models.enum_helpers import pg_enum


class AiDraftType(enum.StrEnum):
    EMAIL_REPLY = "email_reply"
    OUTBOUND_EMAIL = "outbound_email"
    CALL_SCRIPT = "call_script"


class AiDraftStatus(enum.StrEnum):
    PENDING = "pending"
    APPROVED = "approved"
    EDITED_AND_SENT = "edited_and_sent"
    DISCARDED = "discarded"


class AiDraft(Base):
    """A draft generated by an AI agent. Nothing auto-sends — humans approve."""

    __tablename__ = "ai_drafts"

    workspace_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("workspaces.id", ondelete="CASCADE"),
        nullable=False,
    )
    agent_run_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("agent_runs.id", ondelete="SET NULL"),
        nullable=True,
    )
    draft_type: Mapped[AiDraftType] = mapped_column(
        pg_enum(AiDraftType, name="ai_draft_type"),
        nullable=False,
    )
    entity_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    entity_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True), nullable=True
    )
    subject: Mapped[str | None] = mapped_column(String(500), nullable=True)
    body_html: Mapped[str | None] = mapped_column(Text, nullable=True)
    body_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[AiDraftStatus] = mapped_column(
        pg_enum(AiDraftStatus, name="ai_draft_status"),
        nullable=False,
        default=AiDraftStatus.PENDING,
    )
    reviewed_by_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    __table_args__ = (
        Index("ix_ai_drafts_workspace_id", "workspace_id"),
        Index("ix_ai_drafts_draft_type", "draft_type"),
        Index("ix_ai_drafts_status", "status"),
        Index("ix_ai_drafts_entity_id", "entity_id"),
    )
